spring:
  datasource:
    name: test  #????
    url: jdbc:mysql://localhost:3306/test #url
    username: xiaogang  #???
    password: 123456  #??
    driver-class-name: com.mysql.cj.jdbc.Driver  #???????

